# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69c0960853271c00be9ce7202fe49f0e18314cfd177f8e838db45d7c142b45a5b091203e7714c522ace68c8f088a954b99d5b8d4042c8f4de820e58171b788b

test:
  secret_key_base: 64df5c3a4d6bdca736dc28e3958970c86c6898a33068270ea6252afb0f88cbb2819609bb8c7bb54711b394f7f662a1b8862ef25d5b0b059061f02dc8f2be811b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
